name = "AdaptiveStepSize"
uuid = "7d84fdfd-9968-451e-b556-cbaf6a09f307"
authors = ["pmc4 <117096890+pmc4@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"

[compat]
Enzyme = "0.13.41"
julia = "1.11"
